#!/usr/bin/env bash

set -e

cd "$(dirname ${0})"

NVM_VERSION="${NVM_VERSION:-$(./latest-nvm-version)}"
NODE_VERSION="${NODE_VERSION:-$(./latest-nvm-node-version)}"
DENO_VERSION="${DENO_VERSION:-$(./latest-deno-version)}"

LATEST_WEBSTORM_URL="$(./latest-webstorm-url)"
LATEST_WEBSTORM_VERSION=$(./jetbrains-url-to-version "${LATEST_WEBSTORM_URL}")
WEBSTORM_URL="${WEBSTORM_URL:-${LATEST_WEBSTORM_URL}}"
WEBSTORM_VERSION=$(./jetbrains-url-to-version "${WEBSTORM_URL}")

function isLatestWebStormVersion() {
  [[ "${WEBSTORM_VERSION}" == "${LATEST_WEBSTORM_VERSION}" ]]
}

if isLatestWebStormVersion; then
  POSSIBLY_LATEST_TAG="--tag hugojosefson/webstorm:latest"
else
  POSSIBLY_LATEST_TAG=""
fi

docker build \
  --build-arg NVM_VERSION="${NVM_VERSION}" \
  --build-arg NODE_VERSION="${NODE_VERSION}" \
  --build-arg DENO_VERSION="${DENO_VERSION}" \
  --build-arg WEBSTORM_URL="${WEBSTORM_URL}" \
  --tag hugojosefson/webstorm:${WEBSTORM_VERSION} \
  ${POSSIBLY_LATEST_TAG} \
  .

if [[ "${1}" == "--push" ]]; then
  docker push hugojosefson/webstorm:${WEBSTORM_VERSION}
  isLatestWebStormVersion && docker push hugojosefson/webstorm:latest
fi
