#!/usr/bin/env bash

set -e

CLION_URL="${1:-$($(dirname ${0})/latest-clion-url)}"
INSTALL_DIR="/opt/clion"

mkdir -p "${INSTALL_DIR}"
curl --silent --location "${CLION_URL}" \
  | tar xz \
    --strip-components 1 \
    --directory "${INSTALL_DIR}"

ln -s ${INSTALL_DIR}/bin/clion.sh /usr/local/bin/clion
