#!/usr/bin/env bash

set -euo pipefail
IFS=$'\t\n'

curl --fail --silent 'https://data.services.jetbrains.com/products/releases?code=WS&latest=true&type=release' \
  | jq -r .WS[0].downloads.linux.link

