#!/usr/bin/env bash

set -euo pipefail
IFS=$'\t\n'

curl --fail --silent 'https://data.services.jetbrains.com/products/releases?code=CL&latest=true&type=release' \
  | jq -r .CL[0].downloads.linux.link

